steps:
  - name: "gcr.io/cloud-builders/docker"
    id: Build the container image
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}-${_ENVIRONMENT}:$COMMIT_SHA",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: Push the container image to Container Registry
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}-${_ENVIRONMENT}:$COMMIT_SHA",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    id: Write environment variables
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo 'LOCATION_NAME: "${_REGION}"' >> ./infra/config/${_ENVIRONMENT}.yaml
        echo 'SERVICE_URL: "${_SERVICE_URL}"' >> ./infra/config/${_ENVIRONMENT}.yaml

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: Deploy container image to Cloud Run
    entrypoint: gcloud
    args: 
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}${_SUFFIX}"
      - "--image"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}-${_ENVIRONMENT}:$COMMIT_SHA"
      - "--region"
      - "${_REGION}"
      - "--service-account"
      - "${_SERVICE_NAME}@$PROJECT_ID.iam.gserviceaccount.com"
      - "--allow-unauthenticated"
      - "--min-instances"
      - "${_MIN_INSTANCES}"
      - "--max-instances"
      - "${_MAX_INSTANCES}"
      - "--env-vars-file"
      - "./infra/config/${_ENVIRONMENT}.yaml"

logsBucket: "gs://${_SERVICE_NAME}-${_ENVIRONMENT}/cloud-build-logs"
options:
  logging: GCS_ONLY

substitutions:
  _ENVIRONMENT: "dev"
  _MAX_INSTANCES: "2"
  _MIN_INSTANCES: "0"
  _REGION: "us-east1"
  _SERVICE_NAME: "example-api"
  _SERVICE_URL: ""
  _SUFFIX: "-dev"

images:
  - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}-${_ENVIRONMENT}:$COMMIT_SHA"
